compile:
	gcc ImageFilter.c -o ImageFilter.out -lm

run:
	# ./ImageFilter.out 1 exampleImages/feep.ascii.pgm generateFilter/RAND.filter outputImage/FilteredImage.ascii.pgm
	./ImageFilter.out 1 exampleImages/lena.ascii.pgm generateFilter/RAND.filter outputImage/FilteredImage.ascii.pgm
