# Each result was made by running command: make test

result:
	rm results3b.txt
	echo "<><><><><><><><><><><><>" >> results3b.txt
	echo "dynamicLinkLibraryTest" >> results3b.txt
	echo "<><><><><><><><><><><><>" >> results3b.txt
	echo >> results3b.txt
	echo "Optimalization 0" >> results3b.txt
	cat dynamicLinkLibraryTest/compileSharedLoadedByProgram0.txt >> results3b.txt
	echo >> results3b.txt
	echo >> results3b.txt
	echo "Optimalization 2" >> results3b.txt
	cat dynamicLinkLibraryTest/compileSharedLoadedByProgram2.txt >> results3b.txt
	echo >> results3b.txt
	echo "<><><><><><><><><><><><>" >> results3b.txt
	echo "sharedLibraryTest" >> results3b.txt
	echo "<><><><><><><><><><><><>" >> results3b.txt
	echo >> results3b.txt
	echo "Optimalization 0" >> results3b.txt
	cat sharedLibraryTest/compileSharedLoadedAtStart0.txt >> results3b.txt
	echo >> results3b.txt
	echo >> results3b.txt
	echo "Optimalization 2" >> results3b.txt
	cat sharedLibraryTest/compileSharedLoadedAtStart2.txt >> results3b.txt
	echo >> results3b.txt
	echo "<><><><><><><><><><><><>" >> results3b.txt
	echo "staticLibraryTest" >> results3b.txt
	echo "<><><><><><><><><><><><>" >> results3b.txt
	echo >> results3b.txt
	echo "Optimalization 0" >> results3b.txt
	cat staticLibraryTest/compileStatic0.txt >> results3b.txt
	echo >> results3b.txt
	echo >> results3b.txt
	echo "Optimalization 2" >> results3b.txt
	cat staticLibraryTest/compileStatic2.txt >> results3b.txt
