compileStatic0:
	gcc -o0 UsingLibraryTest.c -static -L. -lLibraryToWorkOnTable -o UsingLibraryTest.out
	./UsingLibraryTest.out 5 15 d c:0:a:2:f:31 > compileStatic0.txt

compileStatic1:
	gcc -o1 UsingLibraryTest.c -static -L. -lLibraryToWorkOnTable -o UsingLibraryTest.out
	./UsingLibraryTest.out 5 15 d c:0:a:2:f:31 > compileStatic1.txt

compileStatic2:
	gcc -o2 UsingLibraryTest.c -static -L. -lLibraryToWorkOnTable -o UsingLibraryTest.out
	./UsingLibraryTest.out 5 15 d c:0:a:2:f:31 > compileStatic2.txt

compileStatic3:
	gcc -o3 UsingLibraryTest.c -static -L. -lLibraryToWorkOnTable -o UsingLibraryTest.out
	./UsingLibraryTest.out 5 15 d c:0:a:2:f:31 > compileStatic3.txt

test:
	./UsingLibraryTest.out 5 15 d c:0:a:2:f:31

clean:
	rm raport2.txt
	rm *.out
