compileSharedLoadedByProgram0:
	gcc -o0 UsingLibraryLoadedByProgramTest.c -ldl -o UsingLibraryLoadedByProgramTest.out
	./UsingLibraryLoadedByProgramTest.out 5 15 d c:0:a:2:f:31 > compileSharedLoadedByProgram0.txt

compileSharedLoadedByProgram1:
	gcc -o1 UsingLibraryLoadedByProgramTest.c -ldl -o UsingLibraryLoadedByProgramTest.out
	./UsingLibraryLoadedByProgramTest.out 5 15 d c:0:a:2:f:31 > compileSharedLoadedByProgram1.txt

compileSharedLoadedByProgram2:
	gcc -o2 UsingLibraryLoadedByProgramTest.c -ldl -o UsingLibraryLoadedByProgramTest.out
	./UsingLibraryLoadedByProgramTest.out 5 15 d c:0:a:2:f:31 > compileSharedLoadedByProgram2.txt

compileSharedLoadedByProgram3:
	gcc -o3 UsingLibraryLoadedByProgramTest.c -ldl -o UsingLibraryLoadedByProgramTest.out
	./UsingLibraryLoadedByProgramTest.out 5 15 d c:0:a:2:f:31 > compileSharedLoadedByProgram3.txt

test:
	./UsingLibraryLoadedByProgramTest.out 5 15 d c:0:a:2:f:31

clean:
	rm raport2.txt
	rm *.out
