compile:
	gcc CommandInterpreter.c -o CommandInterpreter.out

run:
	./CommandInterpreter.out Commands.txt 3 50

failPsRun:
	./CommandInterpreter.out Commands.txt 3 20

delete:
	rm CommandInterpreter.out
