compile:
	gcc -Wall -g ProducerConsumer.c -o ProducerConsumer.out -lpthread

run:
	./ProducerConsumer.out Configuration.txt

dbg:
	valgrind ./ProducerConsumer.out Configuration.txt

remove:
	rm *.out
