# Each result was made by running command: make test

result:
	rm results3a.txt
	echo "<><><><><><><><><><><><>" >> results3a.txt
	echo "dynamicLinkLibraryTest" >> results3a.txt
	echo "<><><><><><><><><><><><>" >> results3a.txt
	echo >> results3a.txt
	cat dynamicLinkLibraryTest/raport2.txt >> results3a.txt
	echo >> results3a.txt
	echo "<><><><><><><><><><><><>" >> results3a.txt
	echo "sharedLibraryTest" >> results3a.txt
	echo "<><><><><><><><><><><><>" >> results3a.txt
	echo >> results3a.txt
	cat sharedLibraryTest/raport2.txt >> results3a.txt
	echo >> results3a.txt
	echo "<><><><><><><><><><><><>" >> results3a.txt
	echo "staticLibraryTest" >> results3a.txt
	echo "<><><><><><><><><><><><>" >> results3a.txt
	echo >> results3a.txt
	cat staticLibraryTest/raport2.txt >> results3a.txt
