compile:
	gcc CatalogOperations.c -o CatalogOperations.out

# run1:
# 	./CatalogOperations.out . e 2018.03.16/23:29:36
#
# run2:
# 	./CatalogOperations.out . l 2018.03.16/23:29:36
#
# run3:
# 	./CatalogOperations.out . h 2018.03.16/23:29:36

run:
	./CatalogOperations.out . a 2018.03.16/23:29:36

delete:
	rm *.out
